// @ts-nocheck
// Real Encore.dev client for frontend
// This will be generated by Encore
import Client from './client-generated.js';

// Create a client instance
const client = new Client(Client.Local);

// Export the client instance for backward compatibility
export default client;

// Also export individual services
export const church = client.church;
export const admin = client.admin;
export const academy = client.academy;
export const fund = client.fund;
export const membership = client.membership;
export const outreach = client.outreach;
export const partnership = client.partnership;
export const payment = client.payment;
export const staff = client.staff;
export const user = client.user;
