// Real Encore.dev client for frontend
// This will be generated by Encore
import Client, { Local } from './client-generated';

// Determine the correct base URL based on environment
const getBaseURL = () => {
  // Production URL from environment variable
  const productionURL = import.meta.env.VITE_CLIENT_TARGET;

  if (productionURL) {
    return productionURL;
  }

  // Fallback to local development
  return Local;
};

// Create a client instance with proper URL configuration
const client = new Client(getBaseURL());

// Export the client instance for backward compatibility
export default client;

// Also export individual services
export const church = client.church;
export const admin = client.admin;
export const academy = client.academy;
export const fund = client.fund;
export const membership = client.membership;
export const outreach = client.outreach;
export const partnership = client.partnership;
export const payment = client.payment;
export const staff = client.staff;
export const user = client.user;
