name: Preview Deployment

on:
  pull_request:
    branches: [master, main]

jobs:
  preview-backend:
    name: Preview Encore Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Encore CLI
        run: |
          curl -L https://encore.dev/install.sh | bash
          echo "$HOME/.encore/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: npm install

      - name: Build Encore backend
        run: encore build

      - name: Deploy Preview to Encore Cloud
        env:
          ENCORE_TOKEN: ${{ secrets.ENCORE_TOKEN }}
        run: |
          if [ -z "$ENCORE_TOKEN" ]; then
            echo "No ENCORE_TOKEN provided. Skipping backend deploy."
            exit 0
          fi
          encore auth login --token=$ENCORE_TOKEN
          # For preview deployments, we'll just build and test
          echo "Backend built successfully for preview"

  preview-frontend:
    name: Preview Vercel Frontend
    runs-on: ubuntu-latest
    needs: preview-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: ./frontend
        run: bun install

      - name: Build frontend
        working-directory: ./frontend
        run: bun run build

      - name: Deploy Preview to Vercel
        working-directory: ./frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm install -g vercel
          vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
          vercel build --token=$VERCEL_TOKEN
          vercel deploy --token=$VERCEL_TOKEN

  comment-preview:
    name: Comment Preview URLs
    runs-on: ubuntu-latest
    needs: [preview-backend, preview-frontend]
    steps:
      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Preview Deployment Ready!**

              **Frontend Preview**: Check Vercel dashboard for preview URL
              **Backend Preview**: Encore backend built successfully

              Preview will be automatically cleaned up when PR is closed.`
            })
